//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFlights.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyFlights.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model;capacity;
        ///Boeing-737-200;130;.
        /// </summary>
        internal static string aircrafts {
            get {
                return ResourceManager.GetString("aircrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id;name_eng;city_eng;country_eng;IATA;ICAO;timeZone
        ///1987;Nuku Hiva Airport;Nuku Hiva;French Polynesia;NHV;NTMD;-9.5
        ///5890;Hiva Oa-Atuona Airport;Hiva-oa;French Polynesia;AUQ;NTMN;-9.5
        ///5891;Ua Pou Airport;Ua Pou;French Polynesia;UAP;NTMP;-9.5
        ///5892;Ua Huka Airport;Ua Huka;French Polynesia;UAH;NTMU;-9.5
        ///24;St. Anthony Airport;St. Anthony;Canada;YAY;CYAY;-3.5
        ///45;Deer Lake Airport;Deer Lake;Canada;YDF;CYDF;-3.5
        ///77;Stephenville Airport;Stephenville;Canada;YJT;CYJT;-3.5
        ///125;Gander International Airport;Gand [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departure;departure_time;arrival;arrival_time;
        ///Boryspil International Airport;02:00;Kharkiv International Airport;04:00
        ///Boryspil International Airport;04:40;Lviv International Airport;7:40
        ///Boryspil International Airport;05:50;Zaporizhzhia International Airport;10:30
        ///Boryspil International Airport;09:15;Odessa International Airport;12:55
        ///Boryspil International Airport;10:10;Donetsk International Airport;13:00
        ///Donetsk International Airport;05:20;Odessa International Airport;09:30
        ///Lviv International Air [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flights {
            get {
                return ResourceManager.GetString("flights", resourceCulture);
            }
        }
    }
}
