// <auto-generated />
namespace EasyFlights.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddcascadeDeeletefororders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcascadeDeeletefororders));
        
        string IMigrationMetadata.Id
        {
            get { return "201704081536091_Add-cascadeDeelete-for-orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
